#services:
#  angular-app:
#    container_name: login-frontapp
#    build: .
#    ports:
#      - "8082:80"
#    networks:
#      - loginappnetwork
#  mysql:
#    image: "mysql:latest"
#    ports:
#      - "3308:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD : root
#      MYSQL_DATABASE : astonvilla
#      MYSQL_PASSWORD : root
#    networks:
#      - loginappnetwork
#networks:
#   loginappnetwork:
services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    #restart: always
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - 8087:8080
    command: start-dev
    depends_on:
      - postgres
    networks:
      - keycloakpostgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - 5432:5432
    volumes:
      - postgres_data_avril_deux:/var
    networks:
      - keycloakpostgres

volumes:
  postgres_data_avril_deux:
networks:
  keycloakpostgres:

