name: build and push docker image to docker hub
on:
  push:
    branches:
      - main
jobs:
  push_to_dockerhub:
    name: push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
        with:
          ref: seance4
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: nourchawebi/angularschool:1.1.${{github.run_number}}
