
name: build and push docker image to docker hub
on:
  push:
    branches:
      - main
jobs:

  push_to_dockerhub:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
      - name : set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name : login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: sadok21/angularmars-app.1.${{github.run_number}}