
name: build and push docker image to docker hub
on:
  push:
    branches:
      - main
jobs:

  push_to_dockerhub:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
      - name : set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name : login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Fail build on High/Criticial Vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          format: table
          scan-ref: .
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1
      - name: build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: sadok21/angularmars-app.1.${{github.run_number}}
      - name: Email notification
        uses: cinotify/github-action@main
        with:
          to: 'sadoksomii20@gmail.com,alyabouhajja58@gmail.com'
          subject: 'Pipeline Completed'
          body: '<em>aloulou bazdig kamel lpipeline fel github action mte3o.</em>'
          type: 'text/html'
        env:
          SMTP_SERVER: smtp.gmail.com
          SMTP_PORT: 587
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}